#############################################################################
# Makefile for building nxwtoolset
# Generated by tmake at 22:11, 2002/12/26
#     Project: nxwtoolset
#    Template: app
#############################################################################

####### Compiler, tools and options

QTDIR	=	/usr/lib/qt3

CC	=	gcc
CXX	=	g++
CFLAGS	=	-pipe -O2 -DNDEBUG -DLINUX -D_REENTRANT -pedantic
CXXFLAGS=	-pipe -O2 -DNDEBUG -DLINUX -D_REENTRANT -pedantic
INCPATH	=	-I$(QTDIR)/include -I/usr/X11R6/include
LINK	=	g++
LFLAGS	=

LIBS	=	$(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib -lqt-mt -lX11 -lm 


MOC	=	$(QTDIR)/bin/moc
UIC	=	$(QTDIR)/bin/uic

TAR	=	tar -cf
GZIP	=	gzip -9f

####### Files

HEADERS =	nxwtoolset.h
SOURCES =	amxCompiler.cpp \
		main.cpp \
		nxwtoolset.cpp
OBJECTS =	amxCompiler.o \
		main.o \
		nxwtoolset.o
INTERFACES =	
UICDECLS =	
UICIMPLS =	
SRCMOC	=	moc_nxwtoolset.cpp
OBJMOC	=	moc_nxwtoolset.o
DIST	=	
TARGET	=	nxwtoolset
INTERFACE_DECL_PATH = .

####### Implicit rules

.SUFFIXES: .cpp .cxx .cc .C .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules


all: $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(LIBS)

moc: $(SRCMOC)

tmake: Makefile

Makefile: nxwtoolset.pro
	tmake nxwtoolset.pro -o Makefile

dist:
	$(TAR) nxwtoolset.tar nxwtoolset.pro $(SOURCES) $(HEADERS) $(INTERFACES) $(DIST)
	$(GZIP) nxwtoolset.tar

clean:
	-rm -f $(OBJECTS) $(OBJMOC) $(SRCMOC) $(UICIMPLS) $(UICDECLS) $(TARGET)
	-rm -f *~ core

####### Sub-libraries


###### Combined headers


####### Compile

amxCompiler.o: amxCompiler.cpp \
		compiler/sclinux.h \
		compiler/sclib.c

main.o: main.cpp \
		nxwtoolset.h

nxwtoolset.o: nxwtoolset.cpp \
		nxwtoolset.h

moc_nxwtoolset.o: moc_nxwtoolset.cpp \
		nxwtoolset.h

moc_nxwtoolset.cpp: nxwtoolset.h
	$(MOC) nxwtoolset.h -o moc_nxwtoolset.cpp

